/******************************************************************************

Welcome to GDB Online.
GDB online is an online compiler and debugger tool for C, C++, Python, Java, PHP, Ruby, Perl,
C#, OCaml, VB, Swift, Pascal, Fortran, Haskell, Objective-C, Assembly, HTML, CSS, JS, SQLite, Prolog.
Code, Compile, Run and Debug online from anywhere in world.

*******************************************************************************/
/* CONSTRUCTORS : These are methods that are invoked to create objects from the class blueprint.It has same name as that of class and is generally used for initialisation of variables.It does not have a return type.
A class name in JAVA consists of compound words or phrases such that the first letter of each internal word is capitalized and rest of the characters in lowercase.*/
class Cuboid
{
	double width;
	double height;
	double depth;
	Cuboid() // constructor
	{
	    width=10;
	    height=29;
	    depth=3;
	}
	 void calculate()
	{
	    double vol;
	    vol=width*height*depth;
	    System.out.println("Volume of cuboid is = "+vol);
	    }
}
/* Need for Constructor : whenever an object is created,it must be constructed usually with legal initial values automatically without being specified by the programmer,this will immensely relieve the progammer from initialising values of objects for large programs.This is done with the help of Constructor of the class,to which the objects belong to.
INVOKING A CONSTRUCTOR: constructor function gets called automatically whenever an object is created.*/
class Cuboid
{
	double width;
	double height;
	double depth;
	Cuboid() // constructor
	{
	    width=10;
	    height=29;
	    depth=3;
	}
	 void calculate()
	{
	    double vol;
	    vol=width*height*depth;
	    System.out.println("Volume of cuboid is = "+vol);
	    }
public static void main(String[] args)
{
    Cuboid obj=new Cuboid();
    obj.calculate();
}
}
/* A default constructor refers to a nullary constructor that is generated by the compiler if no constructors have been defined for the class,which initialises data members with 0 ,null or false corresponding to the datatypes.
It can be categorised as:
IMPLICIT default constructor
EXPLICIT default constructor.*/